@startuml "Bowling Game Kata"
skinparam classAttributeIconSize 0

enum FrameStatus
{
  Strike
  Spare
  Normal
}

class Bowling {
  + CalculateScore(gamePins: string): int
  - GetNumOfPinsDownForEveryRoll(gamePins: string): int[]
  - GetFirstTenFrameStatuses(gamePins: string): FrameStatusEnum[]
}

class Game {
  - TOTAL_PINS: int
  - MAX_FRAME: int

  - pinsRemaining: int
  - frameCount: int
  - isNewFrame: bool
  
  - currentMultiplier: int
  - nextMultiplier: int
  - score: int
  
  + GetScore(): int
  + Roll(number: int): void

  - UpdatePrivateFieldsForNextRoll(): void
  - GetFrameStatus(): FrameStatus
  - IsNextRollANewFrame(): bool
  - UpdateMultipliers(frameStatus: FrameStatus): void
}

Bowling --> FrameStatus
Game --> FrameStatus

@enduml

